### ISSUE TITLE
How do i use the flag override from the originar h265ize?

### ISSUE THREAD

**Issue by GerardPolloRebozado** [adriel/h265ize-docker#2]
New to docker not sure how do you add flags. using -o dont work

**Comment by adriel** [comment]
If I understand you correctly, you add it at the very end.
<img width="445" alt="image" src="https://user-images.githubusercontent.com/154217/201314236-4dbd53bc-03bd-4d5b-8006-73771a1924bb.png">

See: https://github.com/adriel/h265ize-docker#optional-parameters

**Comment by GerardPolloRebozado** [comment]
Oh ok thanks that worked
